'use strict';
// Pure scheduling engine. Times are minutes-from-midnight in [0,1440).
// weekday: 0=Sun..6=Sat. Exclusions with enabled===false are ignored.
// config.fullyRandom => the daily count is itself randomized (3..8 by default).
function parseHHMM(s){ if(typeof s!=='string')throw new Error('time must be "HH:MM"'); const m=/^(\d{1,2}):(\d{2})$/.exec(s.trim()); if(!m)throw new Error('invalid time: '+s); const h=+m[1],min=+m[2]; if(h<0||h>23||min<0||min>59)throw new Error('out of range time: '+s); return h*60+min; }
function formatHHMM(min){ min=((Math.round(min)%1440)+1440)%1440; const h=Math.floor(min/60),m=min%60; return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'); }
function expandExclusion(ex){ const s=parseHHMM(ex.start),e=parseHHMM(ex.end); if(s===e)return[]; if(e>s)return[[s,e]]; return[[s,1440],[0,e]]; }
function activeExclusionSegments(exclusions,weekday){ const segs=[]; for(const ex of exclusions||[]){ if(ex.enabled===false)continue; const days=Array.isArray(ex.days)?ex.days:[]; if(!days.includes(weekday))continue; for(const seg of expandExclusion(ex))segs.push(seg);} return segs; }
function mergeIntervals(intervals){ if(!intervals.length)return[]; const sorted=intervals.slice().sort((a,b)=>a[0]-b[0]); const out=[sorted[0].slice()]; for(let i=1;i<sorted.length;i++){ const last=out[out.length-1],cur=sorted[i]; if(cur[0]<=last[1])last[1]=Math.max(last[1],cur[1]); else out.push(cur.slice()); } return out; }
function complement(blocked){ const free=[]; let cursor=0; for(const [a,b] of blocked){ if(a>cursor)free.push([cursor,a]); cursor=Math.max(cursor,b);} if(cursor<1440)free.push([cursor,1440]); return free; }
function mulberry32(seed){ let a=seed>>>0; return function(){ a|=0;a=(a+0x6D2B79F5)|0; let t=Math.imul(a^(a>>>15),1|a); t=(t+Math.imul(t^(t>>>7),61|t))^t; return ((t^(t>>>14))>>>0)/4294967296; }; }
function effectiveCount(config,rng){ if(config&&config.fullyRandom){ const lo=Math.max(1,Math.floor(config.randomMin||3)); const hi=Math.max(lo,Math.floor(config.randomMax||8)); return lo+Math.floor(rng()*(hi-lo+1)); } return Math.max(0,Math.floor((config&&config.alarmsPerDay)||0)); }
function generateTimesForDay(config,weekday,rng){ rng=rng||Math.random; const N=effectiveCount(config,rng); const g=Math.max(1,Math.floor(config.minGapMinutes!=null?config.minGapMinutes:30)); const blocked=mergeIntervals(activeExclusionSegments(config.exclusions,weekday)); const free=complement(blocked); const freeMinutes=[]; for(const [a,b] of free)for(let m=a;m<b;m++)freeMinutes.push(m); const L=freeMinutes.length; if(N===0||L===0)return{times:[],requested:N,placed:0,capped:N>0}; for(let target=N;target>=1;target--){ for(let attempt=0;attempt<300;attempt++){ const picks=[]; for(let i=0;i<target;i++){ const lo=Math.floor((i*L)/target),hi=Math.floor(((i+1)*L)/target); const span=Math.max(1,hi-lo); const idx=Math.min(L-1,lo+Math.floor(rng()*span)); picks.push(freeMinutes[idx]); } picks.sort((a,b)=>a-b); let ok=true; for(let i=1;i<picks.length;i++){ if(picks[i]-picks[i-1]<g){ok=false;break;} } if(ok)return{times:picks,requested:N,placed:target,capped:target<N}; } } return{times:[freeMinutes[Math.floor(rng()*L)]],requested:N,placed:1,capped:N>1}; }
module.exports={parseHHMM,formatHHMM,expandExclusion,activeExclusionSegments,mergeIntervals,complement,mulberry32,effectiveCount,generateTimesForDay};
